#!/bin/bash

apt-get update

export DEBIAN_FRONTEND=noninteractive

debconf-set-selections <<< 'mariadb-server-10.0 mysql-server/root_password password rootpass'

debconf-set-selections <<< 'mariadb-server-10.0 mysql-server/root_password_again password rootpass'

apt-get -y install mariadb-server


mysql --user=root --password=rootpass -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'10.0.0%' IDENTIFIED BY 'rootpass' WITH GRANT OPTION;"
mysql --user=root --password=rootpass -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%.%.%.%' IDENTIFIED BY 'rootpass' WITH GRANT OPTION;"

service mysql stop

wget https://raw.githubusercontent.com/keithtobin/mariadbazure/master/my.cnf

service mysql start

touch /tmp/cloudinit_was_run
